spring.application.name=smoma


# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/smoma_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=TruthOfVick26!
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Active Directory / LDAP Integration (Configured for ART Server binding)
server.port=8086

spring.ldap.urls=ldap://192.168.0.101:389
spring.ldap.base=dc=art,dc=cm
spring.ldap.username=lucien.mba@art.cm
spring.ldap.password=@Wdsi@2913@

# JWT Configuration
jwt.secret=9a2f8c4e1b7d3a5f8e0c2b4a6f9d1e3c5b7a9f0e2d4c6b8a1f3e5d7c9b0a2f4e
jwt.expiration=28800000